# Generated by Django 5.2.7 on 2026-02-15 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the provider account",
                        max_length=255,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("contabo", "Contabo"),
                            ("digitalocean", "DigitalOcean"),
                        ],
                        help_text="Type of cloud provider",
                        max_length=20,
                    ),
                ),
                (
                    "encrypted_credentials",
                    models.TextField(help_text="Encrypted JSON credentials"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        help_text="Last sync status: success, error",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "providers_provider",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "provider_type"],
                        name="providers_p_user_id_20177c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="providers_p_user_id_8963c5_idx",
                    ),
                ],
            },
        ),
    ]
