# Generated by Django 5.2.7 on 2026-02-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceCustomPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(
                        help_text="Instance ID from the provider", max_length=255
                    ),
                ),
                (
                    "instance_ip",
                    models.CharField(
                        blank=True,
                        help_text="Instance IP address (optional)",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Custom monthly price",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_prices",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Custom Price",
                "verbose_name_plural": "Instance Custom Prices",
                "indexes": [
                    models.Index(
                        fields=["provider", "instance_id"],
                        name="vps_instanc_provide_90f986_idx",
                    ),
                    models.Index(
                        fields=["provider", "instance_ip"],
                        name="vps_instanc_provide_188dac_idx",
                    ),
                ],
                "unique_together": {("provider", "instance_id")},
            },
        ),
    ]
